### ISSUE TITLE
Some specification for install and usage

### ISSUE THREAD

**Issue by carere** [obmarg/ractive-brunch#2]
Hello :)

i just downloaded ractive-brunch in order to handle my templates in my ractive app.

I can't get it to work, i got those following errors:

`04 Sep 15:26:44 - warn: Loading of ractive-brunch failed due to Cannot find module 'Ractive'`

`04 Sep 15:11:10 - error: Initialization error -  Cannot read property 'brunchPluginName' of null`

when i try to build this config file:

```
'use strict';

exports.config = { 

    paths: {
        'public': 'web',
        'watched': ['app/Resources']
    },
    conventions: {
        'assets': /^app\/Resources\/assets/
    },
    files: { 
        javascripts: { 
            joinTo: {
                'js/app.js': /^(app|node_modules\/(ractive|perfect-scrollbar))/
            }
        },
        stylesheets: { 
            joinTo: 'css/style.css'
        },
        templates: {
            joinTo: 'views/templates.ractive'
        }
    },
    plugins: {
        uglify: {
            mangle: false,
            compress: {
                global_defs: {DEBUG: false}
            }
        },
        eslint: {
            pattern: /^app\/.*\.js?$/,
            warnOnly: true
        }
    }
};
```

For info, this is my package.json:

```
{
  "name": "carne",
  "version": "1.0.0",
  "description": "e-commerce website",
  "main": "brunch-config.js",
  "repository": "~/Documents/Sites/Carne",
  "directories": {
    "test": "tests"
  },
  "dependencies": {
    "perfect-scrollbar": "^0.6.12"
  },
  "devDependencies": {
    "babel-brunch": "^6.0.6",
    "brunch": "^2.8.2",
    "eslint": "^3.4.0",
    "eslint-brunch": "^3.8.0",
    "eslint-config-defaults": "^9.0.0",
    "eslint-config-google": "^0.6.0",
    "eslint-config-standard": "^6.0.0",
    "eslint-plugin-promise": "^2.0.1",
    "eslint-plugin-standard": "^2.0.0",
    "sass-brunch": "^2.6.3",
    "uglify-js-brunch": "^2.0.1",
    "ractive": "^0.7.3",
    "ractive-brunch": "^1.0.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "license": "ISC"
}
```

**Comment by obmarg** [comment]
Hey,

Doesn't look like you're doing anything particularly wrong.

However, I threw this plugin together a couple of years ago, and haven't been using ractive much since then.  I suspect that some things have changed in that time that have caused this plugin to break.  You might have a bit more luck with [one of the forks](https://github.com/obmarg/ractive-brunch/network).

In particular, it looks like [this commit](https://github.com/flipstone/ractive-brunch/commit/394f360e3e495ae38277eaf6cb4e3e68b301a702) might fix that first error you're getting.

**Comment by carere** [comment]
Hello,

Thx for the reply, i took a fork of your project (usefulparadigm) and it's just fine.

I closed this thread.
